// Getters
export const GETTERS_INIT_TODOS = "GETTERS_INIT_TODOS";
export const GETTERS_INIT_TODO = "GETTERS_INIT_TODO";
export const GETTERS_ISLOADING = "types.GETTERS_ISLOADING";

// Mutations
export const MUTATE_GET_TODOS = "MUTATE_GET_TODOS";
export const MUTATE_GET_TODO = "MUTATE_GET_TODO";
export const MUTATE_ADD_TODO = "MUTATE_ADD_TODO";
export const MUTATE_UPDATE_TODO = "MUTATE_UPDATE_TODO";
export const MUTATE_REMOVE_TODO = "MUTATE_DELETE_TODO";
export const MUTATE_TOGGLE_ISLOADING = "MUTATE_TOGGLE_ISLOADING";

// Actions
export const ACTION_GET_TODOS = "ACTION_GET_TODOS";
export const ACTION_GET_TODO = "ACTION_GET_TODO";
export const ACTION_ADD_TODO = "ACTION_ADD_TODO";
export const ACTION_UPDATE_TODO = "ACTION_UPDATE_TODO";
export const ACTION_REMOVE_TODO = "ACTION_REMOVE_TODO";
